// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ListActiveRequestLogs(): $CancellablePromise<$models.ReqeustLog[]> {
    return $Call.ByName("codeswitch/services.LogService.ListActiveRequestLogs").then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListCompletedRequestLogs(afterID: number, limit: number): $CancellablePromise<$models.ReqeustLog[]> {
    return $Call.ByName("codeswitch/services.LogService.ListCompletedRequestLogs", afterID, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ProviderDailyStats(platform: string): $CancellablePromise<$models.ProviderDailyStat[]> {
    return $Call.ByID(974013659, platform).then(($result: any) => {
        return $$createType3($result);
    });
}

export function StatsSince(platform: string): $CancellablePromise<$models.LogStats> {
    return $Call.ByID(2831143405, platform).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ReqeustLog.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ProviderDailyStat.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.LogStats.createFrom;
