// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class AppSettings {
    "show_home_title": boolean;
    "auto_start": boolean;
    "auto_connectivity_test": boolean;

    /**
     * 供应商切换通知开关
     */
    "enable_switch_notify": boolean;
    "enable_codex_stream_guard": boolean;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("show_home_title" in $$source)) {
            this["show_home_title"] = false;
        }
        if (!("auto_start" in $$source)) {
            this["auto_start"] = false;
        }
        if (!("auto_connectivity_test" in $$source)) {
            this["auto_connectivity_test"] = false;
        }
        if (!("enable_switch_notify" in $$source)) {
            this["enable_switch_notify"] = false;
        }
        if (!("enable_codex_stream_guard" in $$source)) {
            this["enable_codex_stream_guard"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * AvailabilityConfig 可用性监控高级配置
 * 在可用性页面的"高级配置"弹窗中设置，可选
 */
export class AvailabilityConfig {
    /**
     * 覆盖默认测试模型
     */
    "testModel"?: string;

    /**
     * 覆盖默认测试端点
     */
    "testEndpoint"?: string;

    /**
     * 覆盖默认超时（毫秒）
     */
    "timeout"?: number;

    /** Creates a new AvailabilityConfig instance. */
    constructor($$source: Partial<AvailabilityConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AvailabilityConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AvailabilityConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AvailabilityConfig($$parsedSource as Partial<AvailabilityConfig>);
    }
}

/**
 * CLIConfig CLI 配置数据
 */
export class CLIConfig {
    "platform": CLIPlatform;
    "fields": CLIConfigField[];

    /**
     * 原始文件内容（用于高级编辑）
     */
    "rawContent"?: string;

    /**
     * 多文件内容预览
     */
    "rawFiles"?: CLIConfigFile[];

    /**
     * "json" 或 "toml"
     */
    "configFormat"?: string;


    /**
     * 配置文件路径
     */
    "filePath"?: string;

    /**
     * 可编辑字段的当前值
     */
    "editable"?: { [_ in string]?: any };

    /** Creates a new CLIConfig instance. */
    constructor($$source: Partial<CLIConfig> = {}) {
        if (!("platform" in $$source)) {
            this["platform"] = CLIPlatform.$zero;
        }
        if (!("fields" in $$source)) {
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): CLIConfig {
        const $$createField1_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField1_0($$parsedSource["fields"]);
        }
        if ("rawFiles" in $$parsedSource) {
            $$parsedSource["rawFiles"] = $$createField3_0($$parsedSource["rawFiles"]);
        }
        if ("editable" in $$parsedSource) {
            $$parsedSource["editable"] = $$createField7_0($$parsedSource["editable"]);
        }
        return new CLIConfig($$parsedSource as Partial<CLIConfig>);
    }
}

/**
 * CLIConfigField 配置字段信息
 */
export class CLIConfigField {
    "key": string;
    "value": string;
    "locked": boolean;
    "hint"?: string;

    /**
     * "string", "boolean", "object"
     */
    "type": string;
    "required"?: boolean;

    /** Creates a new CLIConfigField instance. */
    constructor($$source: Partial<CLIConfigField> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIConfigField instance from a string or object.
     */
    static createFrom($$source: any = {}): CLIConfigField {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CLIConfigField($$parsedSource as Partial<CLIConfigField>);
    }
}

/**
 * CLIConfigFile 配置文件预览（用于前端显示原始内容）
 */
export class CLIConfigFile {
    "path": string;

    /**
     * "json", "toml", "env"
     */
    "format"?: string;
    "content": string;

    /** Creates a new CLIConfigFile instance. */
    constructor($$source: Partial<CLIConfigFile> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIConfigFile instance from a string or object.
     */
    static createFrom($$source: any = {}): CLIConfigFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CLIConfigFile($$parsedSource as Partial<CLIConfigFile>);
    }
}

/**
 * CLIConfigSnapshots CLI 配置快照（用于前端对比：当前 vs 预览）
 */
export class CLIConfigSnapshots {
    "currentFiles": CLIConfigFile[];
    "previewFiles": CLIConfigFile[];

    /**
     * "proxy" | "direct"
     */
    "mode": string;

    /** Creates a new CLIConfigSnapshots instance. */
    constructor($$source: Partial<CLIConfigSnapshots> = {}) {
        if (!("currentFiles" in $$source)) {
            this["currentFiles"] = [];
        }
        if (!("previewFiles" in $$source)) {
            this["previewFiles"] = [];
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIConfigSnapshots instance from a string or object.
     */
    static createFrom($$source: any = {}): CLIConfigSnapshots {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("currentFiles" in $$parsedSource) {
            $$parsedSource["currentFiles"] = $$createField0_0($$parsedSource["currentFiles"]);
        }
        if ("previewFiles" in $$parsedSource) {
            $$parsedSource["previewFiles"] = $$createField1_0($$parsedSource["previewFiles"]);
        }
        return new CLIConfigSnapshots($$parsedSource as Partial<CLIConfigSnapshots>);
    }
}

/**
 * CLIPlatform CLI 平台类型
 */
export enum CLIPlatform {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlatformClaude = "claude",
    PlatformCodex = "codex",
};

/**
 * CLITemplate CLI 配置模板
 */
export class CLITemplate {
    "template": { [_ in string]?: any };
    "isGlobalDefault": boolean;

    /** Creates a new CLITemplate instance. */
    constructor($$source: Partial<CLITemplate> = {}) {
        if (!("template" in $$source)) {
            this["template"] = {};
        }
        if (!("isGlobalDefault" in $$source)) {
            this["isGlobalDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLITemplate instance from a string or object.
     */
    static createFrom($$source: any = {}): CLITemplate {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("template" in $$parsedSource) {
            $$parsedSource["template"] = $$createField0_0($$parsedSource["template"]);
        }
        return new CLITemplate($$parsedSource as Partial<CLITemplate>);
    }
}

export class ClaudeProxyStatus {
    "enabled": boolean;
    "base_url": string;

    /** Creates a new ClaudeProxyStatus instance. */
    constructor($$source: Partial<ClaudeProxyStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeProxyStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaudeProxyStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeProxyStatus($$parsedSource as Partial<ClaudeProxyStatus>);
    }
}

/**
 * ConnectivityResult 连通性测试结果
 */
export class ConnectivityResult {
    "providerId": number;
    "providerName": string;
    "platform": string;
    "status": number;
    "subStatus": string;
    "latencyMs": number;
    "lastChecked": time$0.Time;
    "message"?: string;
    "httpCode"?: number;

    /** Creates a new ConnectivityResult instance. */
    constructor($$source: Partial<ConnectivityResult> = {}) {
        if (!("providerId" in $$source)) {
            this["providerId"] = 0;
        }
        if (!("providerName" in $$source)) {
            this["providerName"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("subStatus" in $$source)) {
            this["subStatus"] = "";
        }
        if (!("latencyMs" in $$source)) {
            this["latencyMs"] = 0;
        }
        if (!("lastChecked" in $$source)) {
            this["lastChecked"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectivityResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectivityResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectivityResult($$parsedSource as Partial<ConnectivityResult>);
    }
}

/**
 * ConsoleLog 控制台日志条目
 */
export class ConsoleLog {
    "timestamp": time$0.Time;

    /**
     * INFO, WARN, ERROR
     */
    "level": string;
    "message": string;

    /** Creates a new ConsoleLog instance. */
    constructor($$source: Partial<ConsoleLog> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsoleLog instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsoleLog {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConsoleLog($$parsedSource as Partial<ConsoleLog>);
    }
}

/**
 * DeepLinkImportRequest 深度链接导入请求模型
 */
export class DeepLinkImportRequest {
    /**
     * 协议版本 (e.g., "v1")
     */
    "version": string;

    /**
     * 资源类型 (e.g., "provider")
     */
    "resource": string;

    /**
     * 目标应用 (claude/codex/openai-chat)
     */
    "app": string;

    /**
     * 供应商名称
     */
    "name": string;

    /**
     * 供应商主页
     */
    "homepage": string;

    /**
     * API 端点
     */
    "endpoint": string;

    /**
     * API 密钥
     */
    "apiKey": string;

    /**
     * 可选模型名称
     */
    "model"?: string | null;

    /**
     * 可选备注
     */
    "notes"?: string | null;

    /**
     * Claude Haiku 模型
     */
    "haikuModel"?: string | null;

    /**
     * Claude Sonnet 模型
     */
    "sonnetModel"?: string | null;

    /**
     * Claude Opus 模型
     */
    "opusModel"?: string | null;

    /**
     * Base64 编码的配置
     */
    "config"?: string | null;

    /**
     * 配置格式 (json/toml)
     */
    "configFormat"?: string | null;

    /**
     * 远程配置 URL
     */
    "configUrl"?: string | null;

    /** Creates a new DeepLinkImportRequest instance. */
    constructor($$source: Partial<DeepLinkImportRequest> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("app" in $$source)) {
            this["app"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = "";
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeepLinkImportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DeepLinkImportRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeepLinkImportRequest($$parsedSource as Partial<DeepLinkImportRequest>);
    }
}

/**
 * EndpointLatency 端点延迟测试结果
 */
export class EndpointLatency {
    /**
     * 端点 URL
     */
    "url": string;

    /**
     * 延迟（毫秒），nil 表示失败
     */
    "latency": number | null;

    /**
     * HTTP 状态码
     */
    "status"?: number | null;

    /**
     * 错误信息
     */
    "error"?: string | null;

    /** Creates a new EndpointLatency instance. */
    constructor($$source: Partial<EndpointLatency> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("latency" in $$source)) {
            this["latency"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointLatency instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointLatency {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EndpointLatency($$parsedSource as Partial<EndpointLatency>);
    }
}

/**
 * EnvConflict 环境变量冲突
 */
export class EnvConflict {
    /**
     * 变量名
     */
    "varName": string;

    /**
     * 变量值
     */
    "varValue": string;

    /**
     * 来源类型: "system" | "file"
     */
    "sourceType": string;

    /**
     * 来源路径
     */
    "sourcePath": string;

    /** Creates a new EnvConflict instance. */
    constructor($$source: Partial<EnvConflict> = {}) {
        if (!("varName" in $$source)) {
            this["varName"] = "";
        }
        if (!("varValue" in $$source)) {
            this["varValue"] = "";
        }
        if (!("sourceType" in $$source)) {
            this["sourceType"] = "";
        }
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvConflict instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvConflict {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvConflict($$parsedSource as Partial<EnvConflict>);
    }
}

/**
 * HealthCheckHistory 健康检查历史（单个 Provider 的时间线）
 */
export class HealthCheckHistory {
    "providerId": number;
    "providerName": string;
    "platform": string;

    /**
     * 历史记录（最近 N 条）
     */
    "items": HealthCheckResult[];

    /**
     * 最新一条
     */
    "latest": HealthCheckResult | null;

    /**
     * 可用率（%）
     */
    "uptime": number;

    /**
     * 平均延迟
     */
    "avgLatencyMs": number;

    /** Creates a new HealthCheckHistory instance. */
    constructor($$source: Partial<HealthCheckHistory> = {}) {
        if (!("providerId" in $$source)) {
            this["providerId"] = 0;
        }
        if (!("providerName" in $$source)) {
            this["providerName"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("latest" in $$source)) {
            this["latest"] = null;
        }
        if (!("uptime" in $$source)) {
            this["uptime"] = 0;
        }
        if (!("avgLatencyMs" in $$source)) {
            this["avgLatencyMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthCheckHistory instance from a string or object.
     */
    static createFrom($$source: any = {}): HealthCheckHistory {
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField3_0($$parsedSource["items"]);
        }
        if ("latest" in $$parsedSource) {
            $$parsedSource["latest"] = $$createField4_0($$parsedSource["latest"]);
        }
        return new HealthCheckHistory($$parsedSource as Partial<HealthCheckHistory>);
    }
}

/**
 * HealthCheckResult 健康检查结果
 */
export class HealthCheckResult {
    "id": number;
    "providerId": number;
    "providerName": string;
    "platform": string;
    "model"?: string;
    "endpoint"?: string;

    /**
     * operational/degraded/failed/validation_failed
     */
    "status": string;

    /**
     * 响应延迟（毫秒）
     */
    "latencyMs": number;

    /**
     * 错误消息
     */
    "errorMessage": string;

    /**
     * 检测时间
     */
    "checkedAt": time$0.Time;

    /** Creates a new HealthCheckResult instance. */
    constructor($$source: Partial<HealthCheckResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("providerId" in $$source)) {
            this["providerId"] = 0;
        }
        if (!("providerName" in $$source)) {
            this["providerName"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("latencyMs" in $$source)) {
            this["latencyMs"] = 0;
        }
        if (!("errorMessage" in $$source)) {
            this["errorMessage"] = "";
        }
        if (!("checkedAt" in $$source)) {
            this["checkedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HealthCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthCheckResult($$parsedSource as Partial<HealthCheckResult>);
    }
}

export class Hotkey {
    /**
     * 热键ID
     */
    "id": number;

    /**
     * 键码
     */
    "keycode": number;

    /**
     * 修饰键
     */
    "modifiers": number;

    /** Creates a new Hotkey instance. */
    constructor($$source: Partial<Hotkey> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("keycode" in $$source)) {
            this["keycode"] = 0;
        }
        if (!("modifiers" in $$source)) {
            this["modifiers"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hotkey instance from a string or object.
     */
    static createFrom($$source: any = {}): Hotkey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Hotkey($$parsedSource as Partial<Hotkey>);
    }
}

export class LogStats {
    "total_requests": number;
    "input_tokens": number;
    "output_tokens": number;
    "reasoning_tokens": number;
    "cache_create_tokens": number;
    "cache_read_tokens": number;
    "series": LogStatsSeries[];

    /** Creates a new LogStats instance. */
    constructor($$source: Partial<LogStats> = {}) {
        if (!("total_requests" in $$source)) {
            this["total_requests"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("cache_create_tokens" in $$source)) {
            this["cache_create_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }
        if (!("series" in $$source)) {
            this["series"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogStats instance from a string or object.
     */
    static createFrom($$source: any = {}): LogStats {
        const $$createField11_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("series" in $$parsedSource) {
            $$parsedSource["series"] = $$createField11_0($$parsedSource["series"]);
        }
        return new LogStats($$parsedSource as Partial<LogStats>);
    }
}

export class LogStatsSeries {
    "day": string;
    "total_requests": number;
    "input_tokens": number;
    "output_tokens": number;
    "reasoning_tokens": number;
    "cache_create_tokens": number;
    "cache_read_tokens": number;

    /** Creates a new LogStatsSeries instance. */
    constructor($$source: Partial<LogStatsSeries> = {}) {
        if (!("day" in $$source)) {
            this["day"] = "";
        }
        if (!("total_requests" in $$source)) {
            this["total_requests"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("cache_create_tokens" in $$source)) {
            this["cache_create_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogStatsSeries instance from a string or object.
     */
    static createFrom($$source: any = {}): LogStatsSeries {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogStatsSeries($$parsedSource as Partial<LogStatsSeries>);
    }
}

export class MCPServer {
    "name": string;
    "type": string;
    "command"?: string;
    "args"?: string[];
    "env"?: { [_ in string]?: string };
    "url"?: string;
    "website"?: string;
    "tips"?: string;
    "enable_platform": string[];
    "enabled_in_claude": boolean;
    "enabled_in_codex": boolean;
    "missing_placeholders": string[];

    /** Creates a new MCPServer instance. */
    constructor($$source: Partial<MCPServer> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("enable_platform" in $$source)) {
            this["enable_platform"] = [];
        }
        if (!("enabled_in_claude" in $$source)) {
            this["enabled_in_claude"] = false;
        }
        if (!("enabled_in_codex" in $$source)) {
            this["enabled_in_codex"] = false;
        }
        if (!("missing_placeholders" in $$source)) {
            this["missing_placeholders"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPServer instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPServer {
        const $$createField3_0 = $$createType18;
        const $$createField4_0 = $$createType4;
        const $$createField8_0 = $$createType18;
        const $$createField12_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField3_0($$parsedSource["args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField4_0($$parsedSource["env"]);
        }
        if ("enable_platform" in $$parsedSource) {
            $$parsedSource["enable_platform"] = $$createField8_0($$parsedSource["enable_platform"]);
        }
        if ("missing_placeholders" in $$parsedSource) {
            $$parsedSource["missing_placeholders"] = $$createField12_0($$parsedSource["missing_placeholders"]);
        }
        return new MCPServer($$parsedSource as Partial<MCPServer>);
    }
}

/**
 * ManualTestResult 手动测试结果
 */
export class ManualTestResult {
    "success": boolean;
    "latencyMs": number;
    "httpCode": number;
    "message": string;
    "rawResult"?: string;
    "httpResponse"?: string;

    /** Creates a new ManualTestResult instance. */
    constructor($$source: Partial<ManualTestResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("latencyMs" in $$source)) {
            this["latencyMs"] = 0;
        }
        if (!("httpCode" in $$source)) {
            this["httpCode"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManualTestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ManualTestResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ManualTestResult($$parsedSource as Partial<ManualTestResult>);
    }
}

/**
 * Prompt 自定义提示词
 */
export class Prompt {
    "id": string;
    "name": string;
    "content": string;
    "description"?: string | null;
    "enabled": boolean;
    "createdAt"?: number | null;
    "updatedAt"?: number | null;

    /** Creates a new Prompt instance. */
    constructor($$source: Partial<Prompt> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Prompt instance from a string or object.
     */
    static createFrom($$source: any = {}): Prompt {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Prompt($$parsedSource as Partial<Prompt>);
    }
}

export class Provider {
    /**
     * 修复：使用 int64 支持大 ID 值
     */
    "id": number;
    "name": string;
    "apiUrl": string;
    "apiKey": string;
    "officialSite": string;
    "icon": string;
    "tint": string;
    "accent": string;
    "enabled": boolean;

    /**
     * API 端点路径（可选）- 覆盖平台默认端点
     * 如：GLM 模型需要使用 /chat/completions 而非 /v1/messages
     * 留空则使用平台默认（claude: /v1/messages, codex: /responses）
     */
    "apiEndpoint"?: string;

    /**
     * Responses 协议端点（可选）
     * 当入站请求为 /responses 或 /v1/responses 时优先使用。
     */
    "responsesEndpoint"?: string;

    /**
     * Chat Completions 协议端点（可选）
     * 当入站请求为 /chat/completions 时优先使用。
     */
    "chatEndpoint"?: string;

    /**
     * 模型列表端点（可选）
     * 用于模型监控页面拉取该供应商可用模型列表；留空默认使用 /v1/models。
     */
    "modelsEndpoint"?: string;

    /**
     * 模型白名单 - Provider 原生支持的模型名
     * 使用 map 实现 O(1) 查找，向后兼容（omitempty）
     */
    "supportedModels"?: { [_ in string]?: boolean };

    /**
     * 模型映射 - 外部模型名 -> Provider 内部模型名
     * 支持精确匹配和通配符（如 "claude-*" -> "anthropic/claude-*"）
     */
    "modelMapping"?: { [_ in string]?: string };

    /**
     * 优先级分组 - 数字越小优先级越高（1-10，默认 1）
     * 使用 omitempty 确保零值不序列化，向后兼容
     */
    "level"?: number;

    /**
     * 可用性监控开关 - 在可用性页面配置
     * 启用后才会执行后台健康检查
     */
    "availabilityMonitorEnabled"?: boolean;


    /**
     * 可用性高级配置 - 可选，在可用性页面的"高级配置"中设置
     */
    "availabilityConfig"?: AvailabilityConfig | null;

    /**
     * 认证方式 - bearer / x-api-key / 自定义 Header 名
     * 空值时使用平台默认（claude: x-api-key, codex: bearer）
     */
    "connectivityAuthType"?: string;

    /**
     * [已废弃] 连通性检测开关 - 迁移到 AvailabilityMonitorEnabled
     */
    "connectivityCheck"?: boolean;

    /**
     * [已废弃] 连通性检测模型 - 迁移到 AvailabilityConfig.TestModel
     */
    "connectivityTestModel"?: string;

    /**
     * [已废弃] 连通性检测端点 - 迁移到 AvailabilityConfig.TestEndpoint
     */
    "connectivityTestEndpoint"?: string;

    /** Creates a new Provider instance. */
    constructor($$source: Partial<Provider> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("apiUrl" in $$source)) {
            this["apiUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("officialSite" in $$source)) {
            this["officialSite"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("tint" in $$source)) {
            this["tint"] = "";
        }
        if (!("accent" in $$source)) {
            this["accent"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Provider instance from a string or object.
     */
    static createFrom($$source: any = {}): Provider {
        const $$createField12_0 = $$createType18;
        const $$createField13_0 = $$createType4;
        const $$createField17_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("supportedModels" in $$parsedSource) {
            $$parsedSource["supportedModels"] = $$createField12_0($$parsedSource["supportedModels"]);
        }
        if ("modelMapping" in $$parsedSource) {
            $$parsedSource["modelMapping"] = $$createField13_0($$parsedSource["modelMapping"]);
        }
        if ("availabilityConfig" in $$parsedSource) {
            $$parsedSource["availabilityConfig"] = $$createField17_0($$parsedSource["availabilityConfig"]);
        }
        return new Provider($$parsedSource as Partial<Provider>);
    }
}

export class ProviderDailyStat {
    "provider": string;
    "total_requests": number;
    "successful_requests": number;
    "failed_requests": number;
    "success_rate": number;
    "input_tokens": number;
    "output_tokens": number;
    "reasoning_tokens": number;
    "cache_create_tokens": number;
    "cache_read_tokens": number;

    /** Creates a new ProviderDailyStat instance. */
    constructor($$source: Partial<ProviderDailyStat> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("total_requests" in $$source)) {
            this["total_requests"] = 0;
        }
        if (!("successful_requests" in $$source)) {
            this["successful_requests"] = 0;
        }
        if (!("failed_requests" in $$source)) {
            this["failed_requests"] = 0;
        }
        if (!("success_rate" in $$source)) {
            this["success_rate"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("cache_create_tokens" in $$source)) {
            this["cache_create_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderDailyStat instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderDailyStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderDailyStat($$parsedSource as Partial<ProviderDailyStat>);
    }
}

/**
 * ProviderTimeline Provider 时间线（用于前端展示）
 */
export class ProviderTimeline {
    "providerId": number;
    "providerName": string;
    "platform": string;
    "availabilityMonitorEnabled": boolean;
    /**
     * 高级配置
     */
    "availabilityConfig"?: AvailabilityConfig | null;

    /**
     * 历史记录
     */
    "items": HealthCheckResult[];

    /**
     * 最新一条
     */
    "latest": HealthCheckResult | null;

    /**
     * 可用率
     */
    "uptime": number;

    /**
     * 平均延迟
     */
    "avgLatencyMs": number;

    /** Creates a new ProviderTimeline instance. */
    constructor($$source: Partial<ProviderTimeline> = {}) {
        if (!("providerId" in $$source)) {
            this["providerId"] = 0;
        }
        if (!("providerName" in $$source)) {
            this["providerName"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("availabilityMonitorEnabled" in $$source)) {
            this["availabilityMonitorEnabled"] = false;
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("latest" in $$source)) {
            this["latest"] = null;
        }
        if (!("uptime" in $$source)) {
            this["uptime"] = 0;
        }
        if (!("avgLatencyMs" in $$source)) {
            this["avgLatencyMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderTimeline instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderTimeline {
        const $$createField5_0 = $$createType22;
        const $$createField6_0 = $$createType12;
        const $$createField7_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("availabilityConfig" in $$parsedSource) {
            $$parsedSource["availabilityConfig"] = $$createField5_0($$parsedSource["availabilityConfig"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField6_0($$parsedSource["items"]);
        }
        if ("latest" in $$parsedSource) {
            $$parsedSource["latest"] = $$createField7_0($$parsedSource["latest"]);
        }
        return new ProviderTimeline($$parsedSource as Partial<ProviderTimeline>);
    }
}

export class ReqeustLog {
    "id": number;

    /**
     * claude、openai-responses 或 openai-chat
     */
    "platform": string;
    "model": string;

    /**
     * provider name
     */
    "provider": string;
    "relay_key_id": string;
    "relay_key_name": string;
    "http_code": number;
    "input_tokens": number;
    "output_tokens": number;
    "cache_create_tokens": number;
    "cache_read_tokens": number;
    "reasoning_tokens": number;
    "is_stream": boolean;
    "duration_sec": number;
    "created_at": string;

    /** Creates a new ReqeustLog instance. */
    constructor($$source: Partial<ReqeustLog> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("relay_key_id" in $$source)) {
            this["relay_key_id"] = "";
        }
        if (!("relay_key_name" in $$source)) {
            this["relay_key_name"] = "";
        }
        if (!("http_code" in $$source)) {
            this["http_code"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("cache_create_tokens" in $$source)) {
            this["cache_create_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("is_stream" in $$source)) {
            this["is_stream"] = false;
        }
        if (!("duration_sec" in $$source)) {
            this["duration_sec"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReqeustLog instance from a string or object.
     */
    static createFrom($$source: any = {}): ReqeustLog {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReqeustLog($$parsedSource as Partial<ReqeustLog>);
    }
}

/**
 * RetryConfig 重试配置（供 proxyHandler 使用）
 */
export class RetryConfig {
    /**
     * 失败阈值
     */
    "FailureThreshold": number;

    /**
     * 重试等待时间（秒）
     */
    "RetryWaitSeconds": number;

    /**
     * 去重窗口（秒）
     */
    "DedupeWindowSeconds": number;

    /** Creates a new RetryConfig instance. */
    constructor($$source: Partial<RetryConfig> = {}) {
        if (!("FailureThreshold" in $$source)) {
            this["FailureThreshold"] = 0;
        }
        if (!("RetryWaitSeconds" in $$source)) {
            this["RetryWaitSeconds"] = 0;
        }
        if (!("DedupeWindowSeconds" in $$source)) {
            this["DedupeWindowSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RetryConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): RetryConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RetryConfig($$parsedSource as Partial<RetryConfig>);
    }
}

export class Skill {
    "key": string;
    "name": string;
    "description": string;
    "directory": string;
    "readme_url": string;
    "installed": boolean;

    /**
     * 新增字段
     * 是否启用（从 SKILL.md 读取）
     */
    "enabled": boolean;

    /**
     * 许可证文件路径
     */
    "license_file"?: string;

    /**
     * "claude" | "codex"
     */
    "platform"?: string;

    /**
     * "user" | "project"
     */
    "install_location"?: string;

    /**
     * 仓库字段
     */
    "repo_owner"?: string;
    "repo_name"?: string;
    "repo_branch"?: string;

    /** Creates a new Skill instance. */
    constructor($$source: Partial<Skill> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("readme_url" in $$source)) {
            this["readme_url"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Skill instance from a string or object.
     */
    static createFrom($$source: any = {}): Skill {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Skill($$parsedSource as Partial<Skill>);
    }
}

export class installRequest {
    "directory": string;
    "repo_owner": string;
    "repo_name": string;
    "repo_branch": string;

    /**
     * "claude" | "codex"
     */
    "platform": string;

    /**
     * "user" | "project"
     */
    "location": string;

    /** Creates a new installRequest instance. */
    constructor($$source: Partial<installRequest> = {}) {
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("repo_owner" in $$source)) {
            this["repo_owner"] = "";
        }
        if (!("repo_name" in $$source)) {
            this["repo_name"] = "";
        }
        if (!("repo_branch" in $$source)) {
            this["repo_branch"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("location" in $$source)) {
            this["location"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new installRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): installRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new installRequest($$parsedSource as Partial<installRequest>);
    }
}

export class skillRepoConfig {
    "owner": string;
    "name": string;
    "branch": string;
    "enabled": boolean;

    /** Creates a new skillRepoConfig instance. */
    constructor($$source: Partial<skillRepoConfig> = {}) {
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new skillRepoConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): skillRepoConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new skillRepoConfig($$parsedSource as Partial<skillRepoConfig>);
    }
}

// Private type creation functions
const $$createType0 = CLIConfigField.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = CLIConfigFile.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = HealthCheckResult.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Nullable($$createType11);
const $$createType14 = LogStatsSeries.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType18 = $Create.Map($Create.Any, $Create.Any);
const $$createType21 = AvailabilityConfig.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
